source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'sprockets', '2.11.0'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'will_paginate'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'json', '~> 1.8.1'
gem 'pg'
gem 'sidekiq'
gem 'sinatra', require: false
gem 'slim'
gem 'fog'
gem 'capistrano', '~> 3.1'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
gem 'unicorn'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'faker'
